### ISSUE TITLE
fpc-mqtt-client

### ISSUE THREAD

**Issue by John7505** [prof7bit/fpc-mqtt-client#1]
**Great Lib**.
 However I do get some range errors at **WriteByte(X)**;

procedure TMQTTStream.WriteInt16Big(X: UInt16);
begin
  // Ch. 1.5.2
  WriteByte(X shr 8);
  WriteByte(X);
end;

**Comment by prof7bit** [comment]
Fixed in 43802336f4c4078848969e634b7dca2d02af8b80
